### ISSUE TITLE
Definition of genes/sequences included in the ambiguity 

### ISSUE THREAD

**Issue by mihuber** [ozagordi/MinVar#20]
The question arose on which genes the ambiguity score is calculated. Also env sequences might be included in a sample, however, the ambiquity score should only be calculated on pol genes.
Further, in the reports there are sometimes several caculations (for several contigs with coverage above threshold I assume). I think we also need to clarify this.

**Comment by ozagordi** [comment]
> The question arose on which genes the ambiguity score is calculated. Also env sequences might be included in a sample, however, the ambiquity score should only be calculated on pol genes.
> 
Has this been clarified? Whole pol (we don’t cover it) or just protease? I’m not sure we need to address this until we’re sure what should go into the calculation. Further, I don’t want to make something that only works with our exact amplicon.

> Further, in the reports there are sometimes several caculations (for several contigs with coverage above threshold I assume). I think we also need to clarify this.
> 
Where?

**Comment by mihuber** [comment]
> > The question arose on which genes the ambiguity score is calculated. Also env sequences might be included in a sample, however, the ambiquity score should only be calculated on pol genes.
> > 
> Has this been clarified? Whole pol (we don’t cover it) or just protease? I’m not sure we need to address this until we’re sure what should go into the calculation. Further, I don’t want to make something that only works with our exact amplicon.

Ambiguity score according to Kouyos et al. In the summary he writes "the fraction of ambiguous nucleotides in partial pol sequences”, but in the methods "All laboratories perform population-based sequencing of the full protease gene and at minimum codons 28–225 of the reverse transcriptase gene by means of commercial assays”.
As I understand, we should include as much sequence (partial) as we have from the PRRT amplicon. Not sure to include the INT amplicon (according to summary yes, according to methods no). Of course exclude ENV.

@ Jürg and Cyril: With or without INT?



> > Further, in the reports there are sometimes several caculations (for several contigs with coverage above threshold I assume). I think we also need to clarify this.
> > 
> Where?

e.g. Sample 180131_M02081_0263_000000000-BHCM4-5_RESISTANCE 

Ambiguity score

Computed on regions of coverage higher than 100.
• score: 1.99 % (26 of 1304 total nucleotides)
• score: 1.64 % (129 of 7866 total nucleotides)


Cyril showed me an other sample today with even three contigs.

**Comment by ozagordi** [comment]
> e.g. Sample 180131_M02081_0263_000000000-BHCM4-5_RESISTANCE 
> 
> Ambiguity score
> 
> Computed on regions of coverage higher than 100.
> • score: 1.99 % (26 of 1304 total nucleotides)
> • score: 1.64 % (129 of 7866 total nucleotides)
> 

Is this HIV or HCV? I know where it’s written. But where would you like it better explained and how?


> Cyril showed me an other sample today with even three contigs.

The reason why I kept it like this is because it adapts to several situations: single amplicon, two or more amplicons, both overlapping and not overlapping. The user knows the PCR design and “reads” what was covered and what not. Is this for us or for the physicians?

**Comment by mihuber** [comment]
Yes, I understand, but final users are the physicians. They don’t know the PCR design and need a single number.
If the ambiguity score should only be calculated on PRRT, then the problem of multiple amplicons should not arise.

**Comment by mihuber** [comment]
We should only calculate it for PRRT up to approx. position AA335. Only this is established with the Kouyos paper.

To see whether we can/should enlarge the region we could make a comparison of the ambiguity score of PRRT vs IN based on the Sanger sequencing. Only then I would decide. May be Cyril can prepare a set of sequences for this?


Am 09.02.2018 um 16:30 schrieb Michael Huber <huber.michael@virology.uzh.ch>:

> 
>>> The question arose on which genes the ambiguity score is calculated. Also env sequences might be included in a sample, however, the ambiquity score should only be calculated on pol genes.
>>> 
>> Has this been clarified? Whole pol (we don’t cover it) or just protease? I’m not sure we need to address this until we’re sure what should go into the calculation. Further, I don’t want to make something that only works with our exact amplicon.
> 
> Ambiguity score according to Kouyos et al. In the summary he writes "the fraction of ambiguous nucleotides in partial pol sequences”, but in the methods "All laboratories perform population-based sequencing of the full protease gene and at minimum codons 28–225 of the reverse transcriptase gene by means of commercial assays”.
> As I understand, we should include as much sequence (partial) as we have from the PRRT amplicon. Not sure to include the INT amplicon (according to summary yes, according to methods no). Of course exclude ENV.
> 
> @ Jürg and Cyril: With or without INT?
> 
> 
> 
>>> Further, in the reports there are sometimes several caculations (for several contigs with coverage above threshold I assume). I think we also need to clarify this.
>>> 
>> Where?
> 
> e.g. Sample 180131_M02081_0263_000000000-BHCM4-5_RESISTANCE 
> 
> Ambiguity score
> 
> Computed on regions of coverage higher than 100.
> • score: 1.99 % (26 of 1304 total nucleotides)
> • score: 1.64 % (129 of 7866 total nucleotides)
> 
> 
> Cyril showed me an other sample today with even three contigs.
