### ISSUE TITLE
MinVar Reference Sequences

### ISSUE THREAD

**Issue by matdoering** [ozagordi/MinVar#23]
I wanted to use MinVar to map some gag/env sequences. However, the reference sequences that are used for determining variants are just for the pol region. Would it be possible to use the full genome reference instead? Otherwise MinVar can't be used because consensus can't be formed (no VCF file is created) resulting in an error. To avoid this problem, I had to manually replace the references (subtype_references) and stop the pipeline early before resistance calling is performed. There, I also noticed another problem which is due to the reference sequences. The consensus sequences have been generated with LANL and by default it places a question mark (?) if the evidence for a nucleotide is not strong enough. Thus, some of the reference sequences defined in MinVar contain characters that are not supported by the FastaReader. This results in errors if the full genome sequences containing gaps are used. Of course, the error doesn't occur when only the pol reference is used ...

The file with the question marks is _HIV1_CON_2002_genome_DNA.fasta_ in the database folder.

**Comment by ozagordi** [comment]
Thanks for pointing out the question marks.

At the moment, I don't plan to extend the region of interest to gag/env: indels there are more complicated and I would need extensive testing before releasing something as reliable as current version. Further, the primary goal of MinVar is to find drug resistance mutations. One more reason to stick to these regions.

But it seems you already found a possible solution. `HIV1_CON_2002_genome_DNA.fasta` is never used as it is in the code. It was used to create `subtype_references.fasta` that is then used by the program.

Closing this for now, but feel free to add feedback.
